# Generated by Django 3.2.4 on 2021-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=225)),
                ('price', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
            ],
        ),
    ]
