# Generated by Django 3.2.4 on 2021-06-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210616_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderItems',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(null=True),
        ),
    ]
