# Generated by Django 3.2.4 on 2021-06-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_items_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subTotal',
            new_name='subtotal',
        ),
    ]
